# Generated by Django 6.1.1 on 2026-09-26 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('pedagogie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_evaluation', models.CharField(choices=[('INTERROGATION', 'Interrogation écrite'), ('DEVOIR', 'Devoir surveillé'), ('COMPOSITION', 'Composition'), ('QCM_LIGNE', 'QCM en ligne')], max_length=15)),
                ('bareme_total', models.DecimalField(decimal_places=2, default=20, help_text='Note maximale de cette évaluation (souvent /20)', max_digits=5)),
                ('coefficient', models.PositiveIntegerField(default=1, help_text='Coefficient de cette évaluation dans la moyenne')),
                ('duree_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('est_en_ligne', models.BooleanField(default=False, help_text='Si True, les élèves peuvent y répondre depuis leur espace')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIEE', 'Publiée (visible des élèves)'), ('CLOTUREE', 'Clôturée (réponses fermées)'), ('CORRIGEE', 'Corrigée')], default='BROUILLON', max_length=15)),
                ('date_ouverture', models.DateTimeField(blank=True, help_text='À partir de quand les élèves peuvent commencer à répondre', null=True)),
                ('date_limite', models.DateTimeField(blank=True, help_text='Après cette date/heure, les réponses ne sont plus acceptées', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe_matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='classes.classematiere')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='pedagogie.sequence')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Copie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_obtenue', models.DecimalField(blank=True, decimal_places=2, help_text="Note finale sur le barème de l'évaluation", max_digits=5, null=True)),
                ('statut', models.CharField(choices=[('NON_RENDU', 'Non rendu'), ('SOUMIS', 'Soumis'), ('CORRIGE', 'Corrigé')], default='NON_RENDU', max_length=10)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('commentaire_enseignant', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='classes.eleve')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='evaluations.evaluation')),
            ],
            options={
                'verbose_name': 'Copie',
                'verbose_name_plural': 'Copies',
                'unique_together': {('evaluation', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField()),
                ('enonce', models.TextField(verbose_name='Énoncé de la question')),
                ('type_question', models.CharField(choices=[('QCM', 'Choix multiple (auto-corrigé)'), ('LIBRE', 'Réponse libre (notée manuellement)')], default='QCM', max_length=10)),
                ('points', models.DecimalField(decimal_places=2, default=1, help_text='Points attribués à cette question', max_digits=5)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.evaluation')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['evaluation', 'numero_ordre'],
                'unique_together': {('evaluation', 'numero_ordre')},
            },
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=300)),
                ('est_correct', models.BooleanField(default=False, help_text='Coché si cette proposition est la bonne réponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='evaluations.question')),
            ],
            options={
                'verbose_name': 'Choix de réponse',
                'verbose_name_plural': 'Choix de réponse',
            },
        ),
        migrations.CreateModel(
            name='ReponseEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_reponse', models.TextField(blank=True)),
                ('points_obtenus', models.DecimalField(blank=True, decimal_places=2, help_text='Rempli automatiquement pour le QCM, manuellement pour le libre', max_digits=5, null=True)),
                ('choix_selectionne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reponses_recues', to='evaluations.choix')),
                ('copie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='evaluations.copie')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reponses', to='evaluations.question')),
            ],
            options={
                'verbose_name': "Réponse d'élève",
                'verbose_name_plural': "Réponses d'élèves",
                'unique_together': {('copie', 'question')},
            },
        ),
    ]
