# Generated by Django 6.1.1 on 2026-09-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('niveau', models.CharField(max_length=10)),
                ('annee_scolaire', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('transfere', 'Transféré')], max_length=20)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eleves.classe')),
            ],
        ),
    ]
