# Generated by Django 6.1.1 on 2026-09-26 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0002_alter_etablissement_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Exemple : 2025-2026', max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_active', models.BooleanField(default=False, help_text="Une seule année scolaire doit être 'active' à la fois")),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='Code court, ex : FR, MATH, HG', max_length=10)),
                ('coefficient_defaut', models.PositiveIntegerField(default=1, help_text='Coefficient standard de cette matière (modifiable par classe si besoin)')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Exemple : 7ème A', max_length=50)),
                ('niveau', models.CharField(choices=[('7EME', '7ème année'), ('8EME', '8ème année'), ('9EME', '9ème nnée')], max_length=10)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='classes.anneescolaire')),
                ('enseignant_principal', models.ForeignKey(blank=True, help_text='Enseignant responsable de cette classe (si applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes_principales', to='comptes.enseignant')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='comptes.etablissement')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['annee_scolaire', 'niveau', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(help_text="Numéro d'identification unique de l'élève", max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=150)),
                ('nom_tuteur', models.CharField(blank=True, help_text='Nom du parent ou tuteur légal', max_length=150)),
                ('telephone_tuteur', models.CharField(blank=True, help_text='Utile pour les notifications SMS/WhatsApp de résultats', max_length=20)),
                ('est_actif', models.BooleanField(default=True, help_text="False si l'élève a quitté l'établissement en cours d'année")),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='classes.classe')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['classe', 'nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='ClasseMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveIntegerField(default=1, help_text='Coefficient de cette matière dans CETTE classe précise')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matieres_enseignees', to='comptes.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.matiere')),
            ],
            options={
                'verbose_name': 'Attribution matière-classe',
                'verbose_name_plural': 'Attributions matière-classe',
                'unique_together': {('classe', 'matiere')},
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='matieres',
            field=models.ManyToManyField(related_name='classes', through='classes.ClasseMatiere', to='classes.matiere'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'annee_scolaire', 'etablissement')},
        ),
    ]
