# Generated by Django 6.1.1 on 2026-09-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('7EME', '7ème année'), ('8EME', '8ème année'), ('9EME', '9ème année')], max_length=10),
        ),
    ]
