# Generated by Django 6.1.1 on 2026-09-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classe_niveau'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleve',
            options={'ordering': ['classe', 'prenom', 'nom'], 'verbose_name': 'Élève', 'verbose_name_plural': 'Élèves'},
        ),
    ]
