# Generated by Django 6.1.1 on 2026-10-02 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_eleve_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleve',
            options={'ordering': ['classe', 'nom', 'prenom'], 'verbose_name': 'Élève', 'verbose_name_plural': 'Élèves'},
        ),
        migrations.AddField(
            model_name='eleve',
            name='compte_utilisateur',
            field=models.OneToOneField(blank=True, help_text="Compte de connexion optionnel, donnant accès à l'espace élève (évaluations en ligne). Créé par l'enseignant depuis la fiche de l'élève, pas à l'inscription — tous les élèves n'en ont pas besoin.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_eleve', to=settings.AUTH_USER_MODEL),
        ),
    ]
