# Generated by Django 6.1.1 on 2026-10-04 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_eleve_options_eleve_compte_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine', models.CharField(choices=[('ENSEIGNANT', 'Espace enseignant'), ('ADMIN', "Interface d'administration")], max_length=12)),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='classes.eleve')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Consultation d'élève",
                'verbose_name_plural': 'Journal des consultations',
                'ordering': ['-date_consultation'],
            },
        ),
    ]
