# Generated by Django 6.1.1 on 2026-10-05 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_journalconsultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(blank=True, help_text='Numéro ou nom de la salle (optionnel)', max_length=50)),
                ('classe_matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='classes.classematiere')),
            ],
            options={
                'verbose_name': "Créneau d'emploi du temps",
                'verbose_name_plural': 'Emploi du temps',
                'ordering': ['jour_semaine', 'heure_debut'],
            },
        ),
    ]
