# Generated by Django 6.1.1 on 2026-09-26 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('comptes', '0002_alter_etablissement_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text="Numéro d'ordre de la séquence dans l'année (1, 2, 3...)")),
                ('titre', models.CharField(help_text='Exemple : Le passé composé', max_length=200)),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, '1er trimestre'), (2, '2ème trimestre'), (3, '3ème trimestre')])),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequences', to='classes.classe')),
            ],
            options={
                'verbose_name': 'Séquence',
                'verbose_name_plural': 'Séquences',
                'ordering': ['classe', 'trimestre', 'numero'],
                'unique_together': {('classe', 'numero', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='FichePreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lecon', models.CharField(choices=[('GRAMMAIRE', 'Grammaire'), ('CONJUGAISON', 'Conjugaison'), ('LECTURE', 'Lecture'), ('EXPRESSION_ECRITE', 'Expression écrite'), ('ORTHOGRAPHE', 'Orthographe'), ('VOCABULAIRE', 'Vocabulaire'), ('DICTEE_PREPAREE', 'Dictée préparée'), ('DICTEE_CONTROLE', 'Dictée de contrôle'), ('AUTRE', 'Autre')], max_length=20)),
                ('titre', models.CharField(help_text='Titre précis de la leçon, ex : Le passé composé des verbes du 1er groupe', max_length=200)),
                ('duree_minutes', models.PositiveIntegerField(default=60, help_text='Durée prévue du cours en minutes')),
                ('rappel_lecon_precedente', models.TextField(blank=True, verbose_name='R.L.P. (Rappel de la leçon précédente)')),
                ('objectif_pedagogique_operationnel', models.TextField(help_text="Ce que l'élève doit être capable de faire à la fin du cours", verbose_name='O.P.O. (Objectif Pédagogique Opérationnel)')),
                ('date_prevue', models.DateField(blank=True, help_text='Date prévue pour dispenser ce cours', null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('FINALISEE', 'Finalisée'), ('DISPENSEE', 'Dispensée (cours donné)')], default='BROUILLON', max_length=15)),
                ('genere_par_ia', models.BooleanField(default=False, help_text="True si cette fiche a été générée avec l'assistance IA")),
                ('fichier_pdf', models.CharField(blank=True, help_text='Chemin du fichier PDF exporté (on stocke le chemin, pas le fichier binaire, comme convenu pour ce projet)', max_length=500, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe_matiere', models.ForeignKey(help_text='Précise à la fois la classe ET la matière concernées', on_delete=django.db.models.deletion.PROTECT, related_name='fiches', to='classes.classematiere')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches', to='comptes.enseignant')),
                ('sequence', models.ForeignKey(blank=True, help_text='Optionnel : rattacher cette fiche à une séquence existante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiches', to='pedagogie.sequence')),
            ],
            options={
                'verbose_name': 'Fiche de préparation',
                'verbose_name_plural': 'Fiches de préparation',
                'ordering': ['-date_prevue', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EtapeFiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField(help_text="Position de l'étape dans le déroulement (1, 2, 3...)")),
                ('titre_etape', models.CharField(help_text='Exemple : Motivation, Observation, Conceptualisation...', max_length=150)),
                ('activite_maitre', models.TextField(blank=True, verbose_name='Activité du maître')),
                ('activite_eleve', models.TextField(blank=True, verbose_name="Activité de l'élève")),
                ('duree_minutes', models.PositiveIntegerField(blank=True, help_text='Durée indicative de cette étape précise', null=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='pedagogie.fichepreparation')),
            ],
            options={
                'verbose_name': 'Étape de fiche',
                'verbose_name_plural': 'Étapes de fiche',
                'ordering': ['fiche', 'numero_ordre'],
                'unique_together': {('fiche', 'numero_ordre')},
            },
        ),
    ]
