# Generated by Django 6.1.1 on 2026-10-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepreparation',
            name='type_lecon',
            field=models.CharField(choices=[('GRAMMAIRE', 'Grammaire'), ('CONJUGAISON', 'Conjugaison'), ('LECTURE', 'Lecture'), ('EXPRESSION_ECRITE', 'Expression écrite'), ('ORTHOGRAPHE', 'Orthographe'), ('VOCABULAIRE', 'Vocabulaire'), ('DICTEE_PREPAREE', 'Dictée préparée'), ('DICTEE_CONTROLE', 'Dictée de contrôle'), ('MATHEMATIQUES', 'Mathématiques'), ('CALCUL', 'Calcul'), ('PHYSIQUE', 'Physique'), ('CHIMIE', 'Chimie'), ('MUSIQUE', 'Musique'), ('REDACTION', 'Rédaction'), ('RECITATION', 'Récitation'), ('SPORT', 'Sport'), ('BIOLOGIE', 'Biologie'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
