# Generated by Django 6.1.1 on 2026-09-27 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveSmallIntegerField(choices=[(1, '1er trimestre'), (2, '2ème trimestre'), (3, '3ème trimestre')])),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne pondérée par les coefficients, calculée automatiquement', max_digits=5, null=True)),
                ('rang', models.PositiveIntegerField(blank=True, help_text="Rang de l'élève dans sa classe pour ce trimestre", null=True)),
                ('effectif_classe', models.PositiveIntegerField(blank=True, help_text="Nombre d'élèves de la classe pris en compte dans le classement", null=True)),
                ('appreciation_generale', models.CharField(blank=True, help_text='Exemple : Très bien, Bien, Assez bien, Passable, Insuffisant', max_length=100)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon (calcul en cours)'), ('GENERE', 'Généré (PDF prêt)'), ('PUBLIE', "Publié (visible par l'élève/parent)")], default='BROUILLON', max_length=10)),
                ('fichier_pdf', models.CharField(blank=True, help_text='Chemin du bulletin PDF généré au format DNEB', max_length=500, null=True)),
                ('date_generation', models.DateTimeField(blank=True, help_text='Rempli automatiquement au moment de la génération du PDF', null=True)),
                ('classe', models.ForeignKey(help_text="Classe de l'élève au moment de ce bulletin", on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='classes.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='classes.eleve')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['classe', 'trimestre', 'rang'],
                'unique_together': {('eleve', 'trimestre', 'classe')},
            },
        ),
        migrations.CreateModel(
            name='LigneBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, help_text="Moyenne de l'élève dans cette matière pour le trimestre", max_digits=5, null=True)),
                ('rang_matiere', models.PositiveIntegerField(blank=True, help_text="Optionnel : rang de l'élève dans CETTE matière précise", null=True)),
                ('appreciation', models.CharField(blank=True, help_text='Appréciation courte du professeur pour cette matière', max_length=100)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='bulletins.bulletin')),
                ('classe_matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_bulletin', to='classes.classematiere')),
            ],
            options={
                'verbose_name': 'Ligne de bulletin',
                'verbose_name_plural': 'Lignes de bulletin',
                'ordering': ['bulletin', 'classe_matiere'],
                'unique_together': {('bulletin', 'classe_matiere')},
            },
        ),
    ]
