# Generated by Django 6.1.1 on 2026-09-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignebulletin',
            name='moyenne_composition',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne des compositions du trimestre (une seule si trimestrielle, moyennée si plusieurs compositions mensuelles)', max_digits=5, null=True, verbose_name='Note de composition'),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='moyenne_devoirs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Moyenne des devoirs et interrogations du trimestre, calculée uniquement sur les évaluations où l'élève a une note (les absences ne comptent jamais comme 0)", max_digits=5, null=True, verbose_name='Note de classe'),
        ),
        migrations.AlterField(
            model_name='lignebulletin',
            name='moyenne',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(Note de classe + 2 × Note de composition) / 3 — calculée automatiquement, ne pas modifier à la main', max_digits=5, null=True, verbose_name='Moyenne trimestrielle'),
        ),
    ]
