# Generated by Django 6.1.1 on 2026-09-26 21:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom officiel de l'établissement", max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('KAYES', 'Kayes'), ('KOULIKORO', 'Koulikoro'), ('SIKASSO', 'Sikasso'), ('SEGOU', 'Ségou'), ('MOPTI', 'Mopti'), ('TOMBOUCTOU', 'Tombouctou'), ('GAO', 'Gao'), ('KIDAL', 'Kidal'), ('MENAKA', 'Ménaka'), ('TAOUDENIT', 'Taoudénit'), ('BAMAKO', 'District de Bamako')], default='SIKASSO', max_length=20)),
                ('type_etablissement', models.CharField(choices=[('PUB', 'Public'), ('PRIV', 'Privé'), ('COMM', 'Communautaire'), ('CONF', 'Confessionnel')], default='PUB', max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('GRATUIT', 'Gratuit'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('ETABLISSEMENT', 'Établissement (multi-enseignants)')], max_length=20, unique=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nombre_classes_max', models.PositiveIntegerField(default=1, help_text='Nombre maximum de classes gérables avec ce plan')),
                ('acces_ia_preparation', models.BooleanField(default=False, help_text="Ce plan donne-t-il accès à l'assistance IA pour les fiches ?")),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(help_text='Numéro Mobile Money (Orange Money / Moov Money)', max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro invalide. Format attendu : +22370000000 ou 70000000', regex='^(\\+223)?[67]\\d{7}$')])),
                ('date_debut_abonnement', models.DateField(blank=True, null=True)),
                ('date_fin_abonnement', models.DateField(blank=True, help_text="Date à laquelle l'abonnement actuel expire", null=True)),
                ('est_actif', models.BooleanField(default=True, help_text='Permet de désactiver un compte sans le supprimer')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_enseignant', to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enseignants', to='comptes.etablissement')),
                ('plan_abonnement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enseignants', to='comptes.planabonnement')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moyen_paiement', models.CharField(choices=[('ORANGE', 'Orange Money'), ('MOOV', 'Moov Money'), ('ESPECES', 'Espèces'), ('AUTRE', 'Autre')], max_length=10)),
                ('reference_transaction', models.CharField(blank=True, help_text="Référence renvoyée par l'opérateur Mobile Money", max_length=100)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ECHOUE', 'Échoué')], default='EN_ATTENTE', max_length=15)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='comptes.enseignant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptes.planabonnement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
