# Generated by Django 6.1.1 on 2026-09-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='ville',
            field=models.CharField(help_text="Ville dans laquelle se trouve l'établissement", max_length=100),
        ),
    ]
