# Generated by Django 6.1.1 on 2026-10-02 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_etablissement_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='telephone',
            field=models.CharField(help_text='Numéro Mobile Money (Orange Money / Moov Money)', max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro invalide. Format attendu : +22370000000 ou 70000000', regex='^(\\+223)?[5-9]\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='ville',
            field=models.CharField(max_length=100),
        ),
    ]
